[package]
name = "tui"
version = "0.2.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = { version = "0.29", features = ["event-stream"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
futures = "0.3"
clap = { version = "4.5", features = ["derive"] }
