[package]
name = "hpm"
version = "0.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
anyhow = "1.0.86"
chrono = "0.4.38"
indicatif = "0.17.8"
reqwest = { version = "0.12.5", features = ["blocking"] }
